import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        heading: ['var(--font-raleway)', 'Raleway', 'system-ui', 'sans-serif'],
        body: ['var(--font-source)', 'Source Sans 3', 'system-ui', 'sans-serif'],
        sans: ['var(--font-source)', 'Source Sans 3', 'system-ui', 'sans-serif'],
      },
      colors: {
        'jungle-green': {
          50: 'var(--color-jungle-green-50)',
          100: 'var(--color-jungle-green-100)',
          200: 'var(--color-jungle-green-200)',
          300: 'var(--color-jungle-green-300)',
          400: 'var(--color-jungle-green-400)',
          500: 'var(--color-jungle-green-500)',
          600: 'var(--color-jungle-green-600)',
          700: 'var(--color-jungle-green-700)',
          800: 'var(--color-jungle-green-800)',
          900: 'var(--color-jungle-green-900)',
          950: 'var(--color-jungle-green-950)',
        },
        platinum: {
          50: 'var(--color-platinum-50)',
          100: 'var(--color-platinum-100)',
          200: 'var(--color-platinum-200)',
          300: 'var(--color-platinum-300)',
          400: 'var(--color-platinum-400)',
          500: 'var(--color-platinum-500)',
          600: 'var(--color-platinum-600)',
          700: 'var(--color-platinum-700)',
          800: 'var(--color-platinum-800)',
          900: 'var(--color-platinum-900)',
          950: 'var(--color-platinum-950)',
        },
        'dusk-blue': {
          50: 'var(--color-dusk-blue-50)',
          100: 'var(--color-dusk-blue-100)',
          200: 'var(--color-dusk-blue-200)',
          300: 'var(--color-dusk-blue-300)',
          400: 'var(--color-dusk-blue-400)',
          500: 'var(--color-dusk-blue-500)',
          600: 'var(--color-dusk-blue-600)',
          700: 'var(--color-dusk-blue-700)',
          800: 'var(--color-dusk-blue-800)',
          900: 'var(--color-dusk-blue-900)',
          950: 'var(--color-dusk-blue-950)',
        },
        'regal-navy': {
          50: 'var(--color-regal-navy-50)',
          100: 'var(--color-regal-navy-100)',
          200: 'var(--color-regal-navy-200)',
          300: 'var(--color-regal-navy-300)',
          400: 'var(--color-regal-navy-400)',
          500: 'var(--color-regal-navy-500)',
          600: 'var(--color-regal-navy-600)',
          700: 'var(--color-regal-navy-700)',
          800: 'var(--color-regal-navy-800)',
          900: 'var(--color-regal-navy-900)',
          950: 'var(--color-regal-navy-950)',
        },
        'smart-blue': {
          50: 'var(--color-smart-blue-50)',
          100: 'var(--color-smart-blue-100)',
          200: 'var(--color-smart-blue-200)',
          300: 'var(--color-smart-blue-300)',
          400: 'var(--color-smart-blue-400)',
          500: 'var(--color-smart-blue-500)',
          600: 'var(--color-smart-blue-600)',
          700: 'var(--color-smart-blue-700)',
          800: 'var(--color-smart-blue-800)',
          900: 'var(--color-smart-blue-900)',
          950: 'var(--color-smart-blue-950)',
        },
        orange: {
          50: 'var(--color-jungle-green-50)',
          100: 'var(--color-jungle-green-100)',
          200: 'var(--color-jungle-green-200)',
          300: 'var(--color-jungle-green-300)',
          400: 'var(--color-jungle-green-400)',
          500: 'var(--color-jungle-green-500)',
          600: 'var(--color-jungle-green-600)',
          700: 'var(--color-jungle-green-700)',
          800: 'var(--color-jungle-green-800)',
          900: 'var(--color-jungle-green-900)',
          950: 'var(--color-jungle-green-950)',
        },
        jax: {
          dark: 'var(--color-on-surface)',
          blue: 'var(--color-primary)',
          teal: 'var(--color-secondary)',
          accent: 'var(--color-on-secondary-container)',
          light: 'var(--color-surface-container-lowest)',
        },
        // Design.md Theme Tokens
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        'surface-variant': 'var(--color-surface-variant)',
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(6,30,41,0.06), 0 1px 2px 0 rgba(6,30,41,0.04)',
        'card-hover': '0 4px 12px 0 rgba(6,30,41,0.08), 0 2px 4px 0 rgba(6,30,41,0.04)',
        btn: '0 1px 2px 0 rgba(6,30,41,0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
